import type { ThemeConfigProps } from '@/types';

export const ThemeConfig: ThemeConfigProps = {
  author: 'Gabriel Marín González',
  shortAuthor: 'Gabriel Marín',
  network: [
    {
      type: 'GitHub',
      icon: 'ri:github-fill',
      url: 'https://github.com/amaringonz',
    },
    {
      type: 'LinkedIn',
      icon: 'ri:linkedin-box-fill',
      url: 'https://www.linkedin.com/in/amaringonz',
    },
    {
      type: 'Instagram',
      icon: 'ri:instagram-line',
      url: 'https://www.instagram.com/btwxyz.cr',
    },
    {
      type: 'Email',
      icon: 'ri:mail-line',
      url: 'mailto:amaringonz.dev@gmail.com',
    },
  ],
  experience: [
    {
      expId: 1,
      yearStart: new Date(2023, 6),
      yearEnd: new Date(),
      languages: [
        'JavaScript',
        'TypeScript',
        'HTML & SCSS',
        'React',
        'Next.js',
        'React Native',
        'WordPress',
        'Contentful',
        'Node.js',
        'PHP',
        'Algolia',
        'Jira',
      ],
    },
    {
      expId: 2,
      yearStart: new Date(2021, 2),
      yearEnd: new Date(2023, 2),
      languages: [
        'Shopify',
        'Liquid',
        'HTML & SCSS',
        'JavaScript',
        'jQuery',
        'Shopify API',
        'Google Analytics',
        'PayPal',
        'Tilopay',
        'Jira',
        'Zendesk',
      ],
    },
    {
      expId: 3,
      yearStart: new Date(2019, 4),
      yearEnd: new Date(2021, 1),
      languages: [
        'Next.js',
        'Node.js',
        'MySQL',
        'WebSockets',
        'Redis',
        'Cloudflare',
        'AWS',
        'WAF',
        'JWT',
        'HTML & CSS',
        'JavaScript',
      ],
    },
    {
      expId: 4,
      yearStart: new Date(2017, 1),
      yearEnd: new Date(2019, 4),
      languages: [
        'WordPress',
        'HTML & CSS',
        'JavaScript',
        'Stripe',
        'PayPal',
        'Google Pay',
        'Apple Pay',
        'RBAC',
        'PHP',
        'MySQL',
        'jQuery',
      ],
    },
  ],
  projects: [
    {
      projId: 1,
      previewUrl: 'https://www.amarigonz.dev',
    },
  ],
  availableLanguages: ['es', 'en'],
  defaultLanguage: 'es',
  prefixLanguage: 'as-needed',
};
